DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS developer;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS tbuser;

CREATE TABLE admin (
  aid INTEGER PRIMARY KEY AUTOINCREMENT,
  aname  TEXT UNIQUE NOT NULL,
  apwd TEXT NOT NULL,
  aphone TEXT DEFAULT NULL,
  address TEXT DEFAULT NULL
);

CREATE TABLE developer (
  did INTEGER PRIMARY KEY AUTOINCREMENT,
  dname TEXT UNIQUE NOT NULL,
  dpwd TEXT NOT NULL,
  dphone TEXT DEFAULT NULL,
  dnick TEXT DEFAULT NULL
);

CREATE TABLE game (
  gid INTEGER PRIMARY KEY AUTOINCREMENT,
  gname TEXT NOT NULL,
  name TEXT UNIQUE NOT NULL,
  filename TEXT UNIQUE NOT NULL,
  image TEXT UNIQUE NOT NULL,
  note TEXT DEFAULT NULL,
  version TEXT DEFAULT '1.0',
  star INTEGER DEFAULT 0,
  status INTEGER DEFAULT 0
);

CREATE TABLE score (
  sid INTEGER PRIMARY KEY AUTOINCREMENT,
  uid INTEGER NOT NULL,
  gid INTEGER NOT NULL,
  score INTEGER NOT NULL,
  date TEXT NOT NULL
);

CREATE TABLE tbuser (
  uid INTEGER PRIMARY KEY AUTOINCREMENT,
  uname TEXT UNIQUE NOT NULL,
  upwd TEXT NOT NULL,
  unick TEXT DEFAULT NULL,
  sex TEXT DEFAULT '未知',
  phone TEXT DEFAULT NULL,
  birthday TEXT DEFAULT NULL,
  intro TEXT DEFAULT '暂时没有个人简介。',
  exper INTEGER DEFAULT 0
);